name: Go Build Example

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6'  # Executa a cada 15 minutos, de segunda a sábado

env:
  FILE_NAME: hello-server

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20' # Especifique a versão do Go desejada

    - name: Build Go for Linux
      run: go build ${FILE_NAME}.go

    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20' # Especifique a versão do Go desejada

    - name: Build Go for Windows
      run: |
        $env:GOOS="windows"
        $env:GOARCH="amd64"
        go build ${FILE_NAME}.go

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
