name: Go Build Example

on:
  push:
    branches:
      - main

env:
  FILE_NAME: hello-server

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Go for Linux
      run: go build ${FILE_NAME}.go

    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Go for Windows
      run: GOOS=windows GOARCH=amd64 go build ${FILE_NAME}.go

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v1
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
